### ISSUE TITLE
Adding logo to the Header

### ISSUE THREAD

**Issue by arsiesis** [BeSite/jQuery.mmenu#209]
Hi,
I just discovered your menu there a few days ago and your menu is the best i have see after a lot of research. Thanks for your work !!

The only missing feature for me is the possibility to add a logo to the header.
If the header could be responsive with the image size, that would be perfect !

![2014-10-29_12-20-59](https://cloud.githubusercontent.com/assets/4740228/4824727/c28a1b72-5f5d-11e4-9a8a-e3f8e581e946.png)

I do this by change in _variables.scss : 

	//$mm_headerHeight	: $mm_btnSize * 1,5 !default;
	$mm_headerHeight		: $mm_btnSize * 4.5 !default;

And by change this in jQuery.mmenu.header.scss : 

	.mm-title,
	.mm-prev,
	.mm-next,
	.mm-close
	{
                //padding-top: $mm_headerPaddingTop;
		padding-top: 0;
	}

It is a little "barbarian" and if i change the size of the image, i must recompile scss ...
If anyone have better ideas ? i will be grateful !

**Comment by FrDH** [comment]
In the next version (coming soon), the header will be a bit more flexible, but it won't be responsive to the image size.
Changing the `$mm_headerHeight` in `_variables.scss` is not recommeded because now you can't update the plugin without having to re-do your changes. A better approuch would be to predefine the variable and include the `jquery.mmenu.css` file as explained here:
http://mmenu.frebsite.nl/documentation/custom-css/override-variables.html
