### ISSUE TITLE
White gap in between open menu and page on Android

### ISSUE THREAD

**Issue by jwag789** [BeSite/jQuery.mmenu#260]
It seems when opening the menu, there is a gap that occurs on most of the Android devices. I tested this on my own site at first, but after testing this demo:

http://mmenu.frebsite.nl/demo/menu-contacts.html

on the Browserstack emulators, the same problem occured on the Android devices that were occuring on the actual phones - and these problems did not occur on the iPhone emulator or phone.

After tapping onto the white gap, the menu will then snap back into its correct place and the gap will be gone, but I am wondering how to eliminate it all together.

**Comment by armin-pfaeffle** [comment]
Today, I came accross this problem, too! So I tried a lot of things until I found the problem. It really seems that the stock browser has a rendering bug, but I do not find any similar problems, so it's only a guess.

The combination of `box-shadow` and `transform: translate()` seems to be the problem here. AFAIK `transform` does not consider the width of `text-shadow` property, but in my stock browser (HTC ONE M8), the browser includes this width in its calculations. So remove the `text-shadow` and everything is find.

Well, I know that sometimes you want to have the shadow, but I don't see any useful solution right now. If I find one, I will post it here.

**Comment by armin-pfaeffle** [comment]
The following css style fixes the problem for me. Delete or comment this css style:
```
// jquery.mmenu.css:208
html.mm-opened .mm-page {
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.5); }
```
... and add the following instead:
```
.mm-menu::after {
  content: "";
  position: absolute;
  z-index: 999;
  top: -25%;
  display: block;
  height: 150%;
  
  right: -20px;
  width: 20px;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
  }
```
At the end of the style you can see the properties `right`, `width` and `box-shadow` which all have 20px values. When you want to modify the box-shadow you have to every 20px-value.

I hope that helps you! If you have a better idea, please let me know!

**Comment by FrDH** [comment]
Thanks!

FYI:
Sinse a box-shadow is becomming less standard these days, I'm going to remove it from the core and make it available via an extension for those who still want it.
