### ISSUE TITLE
Height detection when sliding in from the bottom

### ISSUE THREAD

**Issue by danielpataki** [BeSite/jQuery.mmenu#300]
Hi There!

This is a feature request I think as I haven't seen this in the options. Would it be possible to add an auto height option to the menu when it slides in from below? 

![iphone](https://cloud.githubusercontent.com/assets/240318/6366673/8b2d789e-bcc9-11e4-8e03-0424f9c6f1bd.png)

It would be great if in the image above the menu slided in just until the more techniques list item :) Wether or not this gets implemented, this is still the best menu script by a long shot :) 

Thanks!

Daniel

**Comment by FrDH** [comment]
Hi, not a bad idea. Unfortunately this can't be reproduces with CSS only;
The menu needs a fixed height because all panels have position: absolute (and thus no height for their parent). Also, the DIV#mm-blocker that closes the menu onMouseDown/onTouchStart has a height of 100% minus the menu height.

So the only solution would be to measure the height of the currently opened panel and animate the height of the menu to that height and the height of the DIV#mm-blocker to 100% minus that height.

I guess this behavior could be turned into an add-on. I'll see if I can whip something up.

**Comment by danielpataki** [comment]
Hi Fred,

Thanks for giving this some attention :) I'm a bit into other parts of the website just now, but if I can beat you to it I'll try myself :) 

Daniel

**Comment by FrDH** [comment]
Happy to inform you there will be an add-on called "autoHeight" in the next release.

**Comment by danielpataki** [comment]
Wonderful news, thanks so much!

**Comment by FrDH** [comment]
The `js` will look like this:
````javascript
$("#menu").mmenu({
   autoHeight: true
});
````
