### ISSUE TITLE
change the menu slide-in direction

### ISSUE THREAD

**Issue by johnantoni** [BeSite/jQuery.mmenu#424]
Hi,

Is there any way to change the direction of the slide-in from left to right after the page has loaded.

Say re-initialize it and change it's direction without a full page reload?

**Comment by FrDH** [comment]
I guess you could include the "positioning" extension css file separately from the core css file with a media query.
````html
<link href="jquery.mmenu.css" />
<link href="jquery.mmenu.positioning.css" media="screen and (min-width: 500px)" />
````
Now, if you set the `offCanvas.position` to `"right"`, this will only take effect when your screen is wider than 500px.
````javascript
$("#menu").mmenu({
   offCanvas: {
      position: "right"
   }
});
````
Note that if you do this, you'll need to include all css files for extensions and addons separately instead of including the ".all" css file because that would provide the needed css for the `offCanvas.position: "right"` option.
