### ISSUE TITLE
Inline javascript is evaluated twice when mmenu is loaded

### ISSUE THREAD

**Issue by jurglic** [BeSite/jQuery.mmenu#444]
This issue appears when one has inline javascript inside the page. Given this element directly under html body, this javascript runs twice and one gets two alert messages:
`<div><script>alert("HEY");</script></div>`

This can be easily replicated on either of the demo pages - just open the demo html and insert quoted snippet, the element containing inline javascript.

However this doesn't happen if one has `script` element directly under body, not nested in other elements like the parent `div` in example. So this is one way to work around.

Very happy with mmenu otherwise, it's definitely the best such component out there.
Keep up the good work! :+1:

**Comment by FrDH** [comment]
The tutorial states:
>  if you can, please wrap all markup in only one DIV.

This is because in order to be able to push the page out of the viewport and reveal the menu, there must only be one HTML element that is considered to be the page.

If you do not specify what HTML element should be considered to be the page (using the `offCanvas.pageSelector` configuration option), the plugin will assume it is every `DIV` directly inside the body.

In short, you should do either one of the following:
1) Wrap all HTML markup in one DIV.
````html
<body>
    <div>
        <div id="head">...</div>
        <div id="content">...</div>
        <div id="foot">...</div>
    </div>
</body>
````
2) Use the `offCanvas.pageSelector` configuration option to tell specify what HTML element should be considered to be the page.
````javascript
$("#my-menu").mmenu({
   // options
}, {
   // config
   offCanvas: {
      pageSelector: "#my-page"
   }
});
````

**Comment by jurglic** [comment]
Thanks!

The second option perfectly solved our issue!

**Comment by ErEXON** [comment]
I am having the same issue. JS is executing twice.
This is my HTML 
```
<body>
    <content>
        HTML......
    </content>
<script type="javascript" src="something.js"></script>
</body>
```
I also tried using 
```
$(document).ready(function() {
      $("#my-menu").mmenu({
         // options
      }, {
         // configuration
         offCanvas: {
            pageNodetype: "content"
         }
      });
   });
```
BW great work guys.
P.S. - i don't want to go over another library, mmenu is perfect for all my needs
