### ISSUE TITLE
Add an option to close open submenu when another submenu gets opened

### ISSUE THREAD

**Issue by Aybee** [BeSite/jQuery.mmenu#449]
This only belongs to vertical menus. The goal is to only have one submenu open at a time like in an accordion e.g.
- Page 1
  - Subpage 1-1
  - Subpage 1-2
- Page 2
  - Subpage 2-1
  - Subpage 2-2

If submenu of Page 1 opens to show the two subpages next I want to do is to look for subpages of Page 2. When submenu of Page 2 opens then the submenu of Page 1 should close automatically.

**Comment by FrDH** [comment]
That's not possible by default because the submenu you're opening could suddenly "jump" up because another submenu above it would close. Users will be disoriented.

If you really need this behavior, I guess you could bind a function to the "openPanel" method to trigger the "closePanel" method on all other panels:
http://mmenu.frebsite.nl/documentation/api.html

**Comment by Aybee** [comment]
Thank you for your answer.

I thinks this depends on the amount of pages and subpages you have. So it would be nice to give us an optiion to set this by our own. Although I agree that it can lead to disorientation depending on the content/subpages of the menu.

I like to write new CSS to present a horizontal click/touch drop down menu only on large screens. There it is a strange behavior if you touch on an item to see its content and you have to touch again before you touch the next item to see its content.

I will try to code my own solution using your hint. But  an option named "accordion", singleOpen" or whatever would be great.
