### ISSUE TITLE
Hover events or CSS classes won't work when using `span` instead of `a` inside `li`

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#457]
Hover events or CSS classes won't work when using `span` instead of `a` inside `li`.

```html
<li><span>Demo</span><span class="demo">Hover here</span><ul></ul></li>
```

[Reproduction of the issue](http://jsfiddle.net/yr993rwy/8/)
You won't see the `:hover` css class being applied when you pass the mouse hover the text "hover here"

This happens because the final structure after initializing mmenu is the following one:

```html
<li>
    <a class="mm-next mm-fullsubopen" href="#mm-1" data-target="#mm-1"></a>
    <span>Demo</span><span class="demo">Hover here</span>
</li>
```

And the `a` element has a `width:100%` and is literally hover the `span` element preventing access to any element underneath it. 
Instead of having something like this:

```hml
<li>
    <a class="mm-next mm-fullsubopen" href="#mm-1" data-target="#mm-1">
             <span>Demo</span><span class="demo">Hover here</span>
    </a>     
</li>
```

**Comment by FrDH** [comment]
You can do something like this:
````css
a.mm-fullsubopen:hover ~ span.demo {
  font-weight: bold;
}
````
http://jsfiddle.net/wus37tad/

**Comment by alvarotrigo** [comment]
@FrDH that is more a hack than a proper solution.
It doesn't solve other related problems such as the use of hover events in javascript, which was my main problem.

I was trying to apply a Bootstrap tooltip on an icon and I didn't find anyway of doing it.

**Comment by FrDH** [comment]
I agree, but don't think there's a better solution that works because the markup should be consistent for a `SPAN` and an `A`. For example, the searchfield add-on adds the class `mm-fullsubopen` to the `.mm-next` if the `A` on the item does not match the query, but a subitem does.

IMHO having a :hover-state (or tooltip for that matter) is never a good idea for mobile devices. I realize the menu can also be used on desktop websites, but I don't think that measures up to having a consistent markup and css framework.
